volumes:
  db:
  cache:


services:
  http:
    container_name: teste-http
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${DOCKER_HTTP_PORT}:80
    mem_limit: 100M
    volumes:
      - ./:/var/www
      - .docker/nginx/default.d/:/etc/nginx/conf.d/
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - teste
  db:
    container_name: teste-db
    image: mysql:8
    restart: unless-stopped
    mem_limit: 600M
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
        - db:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    networks:
      - teste

  app:
    container_name: teste-api
    build:
      args:
        user: ${DOCKER_USER_ID:-0}
        uid: ${DOCKER_GROUP_ID:-0}
      context: .
      dockerfile: Dockerfile
    image: laravel-api
    restart: unless-stopped
    working_dir: /var/www
    mem_limit: 400M
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - teste



  cache:
    container_name: teste-cache
    image: redis:alpine
    mem_limit: 100M
    ports:
      - ${DOCKER_CACHE_PORT}:6379
    volumes:
      - cache:/data
    restart: unless-stopped
    networks:
      - teste

networks:
  teste:
    driver: bridge
